apps/blog/urls.py
from flask import Blueprint
from . import views
from apps.settings import TEMPLATES_FOLDER, STATIC_FOLDER


bBlog = Blueprint("blog", __name__, static_folder=STATIC_FOLDER, template_folder=TEMPLATES_FOLDER)


bBlog.add_url_rule("/", "index", views.index)
bBlog.add_url_rule("/<int:id>", "post", views.post)
bBlog.add_url_rule("/tag/<string:name>", "tag", views.tags)
bBlog.add_url_rule("/author/<int:uid>", "author", views.author)

apps/blog/models.py
from apps import db
from datetime import datetime


post = db.Table("post",
                db.Column("id", db.Integer, primary_key=True),
                db.Column("article_id", db.Integer,
                          db.ForeignKey("article.id")),
                db.Column("category_id", db.Integer,
                          db.ForeignKey("category.id")),
                )


class Article(db.Model):
    __tablename__ = "article"
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(300))
    body = db.Column(db.Text)
    pubDate = db.Column(db.DateTime, default=datetime.now())
    published = db.Column(db.Boolean, nullable=False, default=False)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    category = db.relationship("Category", secondary=post,
                               backref=db.backref("article", lazy="dynamic"))
    counter = db.relationship("Counters", backref="article", lazy=True)


class Category(db.Model):
    __tablename__ = "category"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))


class Counters(db.Model):
    __tablename__ = "counter"
    id = db.Column(db.Integer, primary_key=True)
    article_id = db.Column(db.Integer, db.ForeignKey('article.id'))
    count = db.Column(db.Integer, nullable=False, default=0)


class BlogSettings(db.Model):
    __tablename__ = "blog_settings"
    id=db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(200), nullable=False)
    description = db.Column(db.Text)

apps/blog/views.py
from flask import render_template
from .models import Article, post, Category
from apps.dashboard.models import Users

article_all = Article.query.filter_by(published=True).all()
category_all = Category.query.all()


def index():
    context = {
        "title": "Home",
        "heading": "Rumah Ilmu",
        "subheading": "Selamat datang di Rumah Ilmu",
        "articles": article_all,
        "category": category_all
    }
    return render_template("blog/index.html", **context)


def post(id):
    article = Article.query.filter_by(id=id).first()
    context = {
        "title": article.title,
        "heading": "Rumah Ilmu",
        "subheading": "Selamat datang di Rumah Ilmu",
        "article": article,
        "category": category_all
    }
    return render_template("blog/post.html", **context)


def tags(name):
    context = {
        "title": "Home",
        "heading": "Rumah Ilmu",
        "subheading": "Selamat datang di Rumah Ilmu",
        "articles": Category.query.filter_by(name=name).all(),
        "category": category_all
    }
    return render_template("blog/index.html", **context)


def author(uid):
    context = {
        "title": "About | Author",
        "heading": "Rumah Ilmu",
        "subheading": "Selamat datang di Rumah Ilmu",
        "user": Users.query.filter_by(id=uid).first()
    }
    return render_template("blog/author.html", **context)

templates/blog/author.html
{% extends "blog/components/base.html" %}

templates/blog/index.html
{% extends "blog/components/base.html" %}
{% block contents %}
<div class="row">
    {% for article in articles %}
    <div class="card mb-4">
        <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
        <div class="card-body">
            <h2 class="card-title">{{ article.title }}</h2>
            <p class="card-text">{{ article.body|truncate(400)|safe }}</p>
            <a href="{{ url_for('blog.post', id=article.id) }}" class="btn btn-primary">Read More &rarr;</a>
        </div>
        <div class="card-footer text-muted">
            Posted on {{ article.pubDate }} by
            {# <a href="{{ url_for('blog.author', uid=article.user.id) }}">{{ article.user.name }}</a> #}
        </div>
    </div>
    {% endfor %}
</div>
<!-- Pagination -->
<ul class="pagination justify-content-center mb-4">
    <li class="page-item">
        <a class="page-link" href="#">&larr; Older</a>
    </li>
    <li class="page-item disabled">
        <a class="page-link" href="#">Newer &rarr;</a>
    </li>
</ul>
{% endblock contents %}

templates/blog/post.html
{% extends "blog/components/base.html" %}
{% block contents %}
          <!-- Title -->
          <h1 class="mt-4">{{ article.title }}</h1>
          <!-- Author -->
          <p class="lead">
            by
            <a href="#">{{ article.user.name }}</a>
          </p>
          <hr>
          <!-- Date/Time -->
          <p>Posted on {{ article.pubDate }}</p>
          <hr>
          <!-- Preview Image -->
          <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">
          <hr>
          {{ article.body|safe }}
            <hr>

          <!-- Comments Form -->
          <div class="card my-4">
            <h5 class="card-header">Leave a Comment:</h5>
            <div class="card-body">
              <form>
                <div class="form-group">
                  <textarea class="form-control" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
              </form>
            </div>
          </div>
{% endblock contents %}