apps/blog/urls.py
from flask import Blueprint
from . import views
from apps.settings import TEMPLATES_FOLDER, STATIC_FOLDER


bBlog = Blueprint("blog", __name__, static_folder=STATIC_FOLDER, template_folder=TEMPLATES_FOLDER)


bBlog.add_url_rule("/", "index", views.index)
bBlog.add_url_rule("/<int:id>", "post", views.post)
bBlog.add_url_rule("/tag/<string:name>", "tag", views.tags)
bBlog.add_url_rule("/author/<int:uid>", "author", views.author)

apps/dashboard/models.py
from apps import db
from flask_login import UserMixin


class Users(db.Model, UserMixin):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), unique=True)
    password = db.Column(db.String(100))
    name = db.Column(db.String(50))
    bio = db.Column(db.Text, nullable=True)
    article = db.relationship("Article", backref="user", lazy=True)

apps/dashboard/forms.py
from flask_wtf import FlaskForm
from wtforms import (StringField, PasswordField, SubmitField, BooleanField, TextAreaField, SelectMultipleField)
from wtforms.validators import DataRequired


class formLogin(FlaskForm):
    username = StringField(label="Username", validators=[
                           DataRequired(message="Username tidak boleh kosong")],)
    password = PasswordField(label="Password", validators=[
                             DataRequired(message="Password tidak boleh kosong")])
    remember = BooleanField(label="Remember user login")
    login = SubmitField()


class formArticle(FlaskForm):
    title = StringField(label="Judul")
    body = TextAreaField(label="body")
    category = TextAreaField(label="kategori")
    save = SubmitField()
    draft = SubmitField()

apps/dashboard/views.py
from flask import (Blueprint, render_template, request,
                   url_for, jsonify, redirect, flash)
from flask_login import (login_user, logout_user, current_user, login_required)
from apps.settings import STATIC_FOLDER, TEMPLATES_FOLDER
from apps import lm, db
from .models import Users
from apps.blog.models import Article, Category, post
from .forms import formLogin, formArticle

bDashboard = Blueprint("dashboard", __name__,
                       static_folder=STATIC_FOLDER, template_folder=TEMPLATES_FOLDER)
lm.session_protection = "strong"


@lm.user_loader
def user_load(uid):
    return Users.query.get(int(uid))


@lm.unauthorized_handler
def unauthorized_callback():
    return redirect(url_for("dashboard.login"))


@bDashboard.route("/", methods=["POST", "GET"])
def login():
    form = formLogin()
    context = {
        "form": form,
    }
    if request.method == "POST":
        if form.validate_on_submit():
            user = Users.query.filter_by(
                username=form.username.data, password=form.password.data).first()
            if user:
                login_user(user)
                return redirect(url_for("dashboard.home"))
        else:
            flash("csrf_token hilang tong")
    elif request.method == "GET":
        if current_user.is_authenticated and current_user.username is not None:
            return redirect(url_for("dashboard.home"))
    return render_template("dashboard/login.html", **context)


@bDashboard.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("dashboard.login"))


@bDashboard.route("/home")
@login_required
def home():
    context = {
        "title": "Home",
        "current_user": current_user
    }
    return render_template("dashboard/index.html", **context)


@bDashboard.route("/article", methods=["GET", "POST"])
@login_required
def article():
    form = formArticle()
    option = request.args.get("option")
    label = request.args.get("label")
    status = request.args.get("status")
    action = request.args.get("action")
    context = {
        "form": form,
        "category": Category.query.all()
    }
    if request.method == "GET":
        if option == "new":
            context["title"] = "Artikel Baru"
            return render_template("dashboard/new_post.html", **context)
        elif option == "all" or option is None:
            if label is not None:
                print(label)
                context["articles"] = Category.query.filter_by(
                    name=label).first().article
            else:
                if status == "published":
                    context["articles"] = Article.query.filter_by(
                        published=True).all()
                    context["title"] = "Diterbitkan"
                elif status == "draft":
                    context["title"] = "Disimpan"
                    context["articles"] = Article.query.filter_by(
                        published=False).all()
            return render_template("dashboard/post.html", **context)

    elif request.method == "POST" and option == "new":
        if form.validate_on_submit():
            if form.save.data is True and form.draft.data is False:
                post = Article(title=form.title.data,
                               body=form.body.data, published=True)
                flash(
                    "<b>{t}</b> ditambahkan ke daftar Diterbitkan".format(t=post.title), category="succes")
            elif form.save.data is False and form.draft.data is True:
                post = Article(title=form.title.data,
                               body=form.body.data, published=False)
                flash(
                    "<b>{t}</b> ditambahkan ke daftar Disimpan".format(t=post.title), category="succes")
            user = Users.query.filter_by(
                username=current_user.username).first()
            post.user = user
            db.session.add(post)
            tags = str(form.category.data).split(",")
            for tag in tags:
                c = Category.query.filter_by(name=tag).first()
                if c.name is not None:
                    post.category.append(c)
            db.session.commit()
            return render_template("dashboard/new_post.html", **context)

@bDashboard.route("/category")
def category():
    pass

templates/dashboard/components/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Dashboard - {{ title }}</title>
  {% include "dashboard/components/css.html" %}
  {%- block css -%}
  {%- endblock css -%}
</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">
  <!-- Navigation-->
  {% include "dashboard/components/navbar.html" %}
  <div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">{{ current_user.username }}</a> on
        </li>
        <li class="breadcrumb-item active">{{ title }}</li>
      </ol>
      {% block contents %}
      {% endblock contents %}
    </div>
    <!-- /.container-fluid-->
    <!-- /.content-wrapper-->
    <footer class="sticky-footer">
      <div class="container">
        <div class="text-center">
          <small>Copyright © Your Website 2018</small>
        </div>
      </div>
    </footer>
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fa fa-angle-up"></i>
    </a>
  </div>
  {% include "dashboard/components/modal.html" %}
  {% include "dashboard/components/js.html" %}
  {%- block js -%}
  {%- endblock js -%}
</body>

</html>

templates/dashboard/components/css.html
<!-- Bootstrap core CSS-->
<link href="{{ url_for(".static", filename="vendor/bootstrap-4.1.1/css/bootstrap.min.css") }}" rel="stylesheet">
<!-- Custom fonts for this template-->
<link href="{{ url_for(".static", filename="vendor/font-awesome/css/font-awesome.min.css") }}" rel="stylesheet" type="text/css">
<!-- Page level plugin CSS-->
<link href="{{ url_for(".static", filename="vendor/datatables/dataTables.bootstrap4.css") }}" rel="stylesheet">
<!-- Custom styles for this template-->
<link href="{{ url_for(".static", filename="css/sb-admin.css") }}" rel="stylesheet">

templates/dashboard/components/js.html
<!-- Bootstrap core JavaScript-->
<script src="{{ url_for(".static", filename="vendor/jquery/jquery.min.js") }}"></script>
<script src="{{ url_for(".static", filename="vendor/bootstrap-4.1.1/js/bootstrap.bundle.min.js") }}"></script>
<!-- Core plugin JavaScript-->
<script src="{{ url_for(".static", filename="vendor/jquery-easing/jquery.easing.min.js") }}"></script>
<!-- Page level plugin JavaScript-->
<script src="{{ url_for(".static", filename="vendor/chart.js/Chart.min.js") }}"></script>
<script src="{{ url_for(".static", filename="vendor/datatables/jquery.dataTables.js") }}"></script>
<script src="{{ url_for(".static", filename="vendor/datatables/dataTables.bootstrap4.js") }}"></script>
<!-- Custom scripts for all pages-->
<script src="{{ url_for(".static", filename="js/sb-admin.min.js") }}"></script>
<!-- Custom scripts for this page-->
<script src="{{ url_for(".static", filename="js/sb-admin-datatables.min.js") }}"></script>

templates/dashboard/components/modal.html
<!-- Logout Modal-->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
        <a class="btn btn-primary" href="{{ url_for('dashboard.logout') }}">Logout</a>
      </div>
    </div>
  </div>
</div>

templates/dashboard/components/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand text-light">Dashboard Rumah Ilmu</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                <a class="nav-link" href="{{ url_for('dashboard.home') }}">
            <i class="fa fa-fw fa-dashboard"></i>
            <span class="nav-link-text">Dashboard</span>
          </a>
            </li>
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Components">
                <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseComponents" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-wrench"></i>
            <span class="nav-link-text">Article</span>
          </a>
                <ul class="sidenav-second-level collapse" id="collapseComponents">
                    <li>
                        <a href="{{ url_for('dashboard.article', option='new') }}">Artikel baru</a>
                    </li>
                    <li>
                        <a href="{{ url_for('dashboard.article', option='all', status='published') }}">Diterbitkan</a>
                    </li>
                    <li>
                        <a href="{{ url_for('dashboard.article', option='all', status='draft') }}">Disimpan</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Kategori">
                <a class="nav-link" href="{{ url_for('dashboard.category') }}">
            <i class="fa fa-fw fa-table"></i>
            <span class="nav-link-text">Kategori</span>
          </a>
            </li>
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Components">
                <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseComponents" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-wrench"></i>
            <span class="nav-link-text">Components</span>
          </a>
                <ul class="sidenav-second-level collapse" id="collapseComponents">
                    <li>
                        <a href="navbar.html">Navbar</a>
                    </li>
                    <li>
                        <a href="cards.html">Cards</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Example Pages">
                <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseExamplePages" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-file"></i>
            <span class="nav-link-text">Example Pages</span>
          </a>
                <ul class="sidenav-second-level collapse" id="collapseExamplePages">
                    <li>
                        <a href="login.html">Login Page</a>
                    </li>
                    <li>
                        <a href="register.html">Registration Page</a>
                    </li>
                    <li>
                        <a href="forgot-password.html">Forgot Password Page</a>
                    </li>
                    <li>
                        <a href="blank.html">Blank Page</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Menu Levels">
                <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti" data-parent="#exampleAccordion">
            <i class="fa fa-fw fa-sitemap"></i>
            <span class="nav-link-text">Menu Levels</span>
          </a>
                <ul class="sidenav-second-level collapse" id="collapseMulti">
                    <li>
                        <a href="#">Second Level Item</a>
                    </li>
                    <li>
                        <a href="#">Second Level Item</a>
                    </li>
                    <li>
                        <a href="#">Second Level Item</a>
                    </li>
                    <li>
                        <a class="nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti2">Third Level</a>
                        <ul class="sidenav-third-level collapse" id="collapseMulti2">
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                            <li>
                                <a href="#">Third Level Item</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
                <a class="nav-link" href="#">
            <i class="fa fa-fw fa-link"></i>
            <span class="nav-link-text">Link</span>
          </a>
            </li>
        </ul>
        <ul class="navbar-nav sidenav-toggler">
            <li class="nav-item">
                <a class="nav-link text-center" id="sidenavToggler">
            <i class="fa fa-fw fa-angle-left"></i>
          </a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
                <i class="fa fa-fw fa-sign-out"></i>Logout
              </a>
            </li>
        </ul>
    </div>
</nav>