apps/blog/urls.py
from flask import Blueprint
from . import views
from apps.settings import TEMPLATES_FOLDER, STATIC_FOLDER


bBlog = Blueprint("blog", __name__, static_folder=STATIC_FOLDER, template_folder=TEMPLATES_FOLDER)


bBlog.add_url_rule("/", "index", views.index)
bBlog.add_url_rule("/<int:id>", "post", views.post)
bBlog.add_url_rule("/tag/<string:name>", "tag", views.tags)
bBlog.add_url_rule("/author/<int:uid>", "author", views.author)

apps/blog/models.py
from apps import db
from datetime import datetime


post = db.Table("post",
                db.Column("id", db.Integer, primary_key=True),
                db.Column("article_id", db.Integer,
                          db.ForeignKey("article.id")),
                db.Column("category_id", db.Integer,
                          db.ForeignKey("category.id")),
                )


class Article(db.Model):
    __tablename__ = "article"
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(300))
    body = db.Column(db.Text)
    pubDate = db.Column(db.DateTime, default=datetime.now())
    published = db.Column(db.Boolean, nullable=False, default=False)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    category = db.relationship("Category", secondary=post,
                               backref=db.backref("article", lazy="dynamic"))
    counter = db.relationship("Counters", backref="article", lazy=True)


class Category(db.Model):
    __tablename__ = "category"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))


class Counters(db.Model):
    __tablename__ = "counter"
    id = db.Column(db.Integer, primary_key=True)
    article_id = db.Column(db.Integer, db.ForeignKey('article.id'))
    count = db.Column(db.Integer, nullable=False, default=0)


class BlogSettings(db.Model):
    __tablename__ = "blog_settings"
    id=db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(200), nullable=False)
    description = db.Column(db.Text)

apps/blog/views.py
from flask import render_template
from .models import Article, post, Category
from apps.dashboard.models import Users

article_all = Article.query.filter_by(published=True).all()
category_all = Category.query.all()


def index():
    context = {
        "title": "Home",
        "heading": "Rumah Ilmu",
        "subheading": "Selamat datang di Rumah Ilmu",
        "articles": article_all,
        "category": category_all
    }
    return render_template("blog/index.html", **context)


def post(id):
    article = Article.query.filter_by(id=id).first()
    context = {
        "title": article.title,
        "heading": "Rumah Ilmu",
        "subheading": "Selamat datang di Rumah Ilmu",
        "article": article,
        "category": category_all
    }
    return render_template("blog/post.html", **context)


def tags(name):
    context = {
        "title": "Home",
        "heading": "Rumah Ilmu",
        "subheading": "Selamat datang di Rumah Ilmu",
        "articles": Category.query.filter_by(name=name).all(),
        "category": category_all
    }
    return render_template("blog/index.html", **context)


def author(uid):
    context = {
        "title": "About | Author",
        "heading": "Rumah Ilmu",
        "subheading": "Selamat datang di Rumah Ilmu",
        "user": Users.query.filter_by(id=uid).first()
    }
    return render_template("blog/author.html", **context)

templates/blog/components/base.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Home - Start Bootstrap Template</title>
    {% include "blog/components/css.html" %}
    {% block css %}
    <link href="{{ url_for('.static', filename='css/blog-home.css') }}" rel="stylesheet">
    {% endblock css %}

  </head>

  <body>
    {% include "blog/components/navbar.html" %}
    <!-- Page Content -->
    <div class="container-fluid">
      <div class="jumbotron jumbotron-fluid bg-dark text-light">
        <div class="container">
          <h1 class="display-4">{{ heading }}</h1>
          <p class="lead">{{ subheading }}</p>
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8">
          {% block contents %}
          {% endblock contents %}
        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Search Widget -->
          <div class="card my-4">
            <h5 class="card-header">Search</h5>
            <div class="card-body">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                  <button class="btn btn-secondary" type="button">Go!</button>
                </span>
              </div>
            </div>
          </div>

          <!-- Categories Widget -->
          <div class="card my-4">
            <h5 class="card-header">Tags</h5>
            <div class="card-body">
              <div class="row">
                <div class="col">
                  <ul class="list-unstyled mb-0">
                    {% for tag in category %}
                    <li>
                      <a href="{{ tag.name }}" class="">{{ tag.name }}</a>
                    </li>
                    {% endfor %}
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <!-- Side Widget -->
          <div class="card my-4">
            <h5 class="card-header">Side Widget</h5>
            <div class="card-body">
              You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
            </div>
          </div>

        </div>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2018</p>
      </div>
      <!-- /.container -->
    </footer>
    {% include "blog/components/js.html" %}
  </body>

</html>

templates/blog/components/css.html
<link rel="stylesheet" type="text/css" href="{{ url_for(".static", filename="vendor/bootstrap-4.1.1/css/bootstrap.min.css") }}">
<link rel="stylesheet" type="text/css" href="{{ url_for(".static", filename="css/base.css") }}"> {% block css %} {% endblock css %}

templates/blog/components/footer.html
<div class="row bg-dark">
    <div class="col-md-6 text-white">
        <h1>footer side left</h1>
    </div>
    <div class="col-md-6 text-white">
        <h1>footer side right</h1>
    </div>
    <div class="col-md-12">
        <p>footer</p>
    </div>
</div>

templates/blog/components/js.html
<script type="text/javascript" src="{{ url_for(".static", filename="vendor/bootstrap-4.1.1/js/bootstrap.min.js") }}"></script>
<script type="text/javascript" src="{{ url_for(".static", filename="vendor/jquery/jquery.min.js") }}"></script>
<script type="text/javascript" src="{{ url_for(".static", filename="vendor/popper/popper-1.14.3.min.js") }}"></script>
{% block js %}
{% endblock js %}

templates/blog/components/navbar.html
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{{ url_for('blog.index') }}">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

templates/blog/components/sidebar.html
<div class="sidebar">
    <form class="form-inline bg-light">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
</div>